name: tulasisolutionssite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_feather_icons: ^2.0.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/home_page.png
    - assets/what.we.do.section.png
    - assets/who.we.serve.section.png
    - assets/how.it.works.section.png
    - assets/faq.final.cta.section.png
    - assets/industries.png


