name: tulasisolutionssite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.2.1
  flutter_feather_icons: ^2.0.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.3.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  go_router: ^14.2.0
  flutter_riverpod: ^2.6.0
  riverpod_annotation: ^2.3.0
  fl_chart: ^0.69.0
  percent_indicator: ^4.1.1
  intl: ^0.19.0
  table_calendar: ^3.1.2
  uuid: ^4.0.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/home_page.png
    - assets/what.we.do.section.png
    - assets/who.we.serve.section.png
    - assets/how.it.works.section.png
    - assets/faq.final.cta.section.png
    - assets/industries.png


